### ISSUE TITLE
Digitize and crop out water in Ontario DEMs

### ISSUE THREAD

**Issue by rsignell-usgs** [rsignell-usgs/karen_work#3]
Because the water surface is changing in time, the drone-derived DEM over water is garbage.
It should be removed because it's very distracting when viewing the 3D model.

**Comment by rsignell-usgs** [comment]
@k-rns, I'm investigating whether this could be done with ArcGIS cloud, 
https://server.arcgis.com/en/cloud/
and whether USGS has access.

If that doesn't work out, you'll have to use a USGS machine.

**Comment by k-rns** [comment]
No problem Rich. I don`t mind coming in. At G-tec, we used Teamviewer a lot to take over a distant computer. So maybe that could also be an option if I need to work remotely on the USGS machine.

**Comment by rsignell-usgs** [comment]
A machine here is being setup for you and we are getting you a login on our network.

**Comment by rsignell-usgs** [comment]
So we don't have access to https://server.arcgis.com/en/cloud/, but @csherwood-usgs is setting up a computer you can use here, or perhaps remotely via remotedesktop.

**Comment by rsignell-usgs** [comment]
@k-rns you are working on this, correct?

**Comment by k-rns** [comment]
@rsignell-usgs , indeed, I'm cutting out these datasets. I already clipped Sandwich datasets from 2017/2016. I'll continue with this on Tuesday
