### ISSUE TITLE
Change credits on sandwich dataset

### ISSUE THREAD

**Issue by rsignell-usgs** [rsignell-usgs/karen_work#6]
Right now the sandwich dataset
http://jetstream.signell.us:8070/mapproxy/melown2015/surface/sandwich/sandwich_dem_resampling
has credits in the bottom right that say "Goddard Space Flight Center and others".   

@k-rns , can you see if you can figure out how to change that to credit: Chris Sherwood, USGS?

**Comment by k-rns** [comment]
@rsignell-usgs, This is probably something in the resource file that needs to be changed, so yep, I'll have a look at this.

**Comment by ladislavhorky** [comment]
Hi @k-rns , I noticed the part about credits was missing in mapproxy docs on github (resource definition), so I added it there: https://github.com/Melown/vts-mapproxy/blob/master/docs/resources.md#basic-resource-layout 

You can see how it can be used e.g. in Mars tutorial: http://vtsdocs.melown.com/en/latest/tutorials/mars-peaks-and-valleys.html#the-global-mosaic .

The credits are one of the things which are actually modifiable in mapproxy resource, so you do not need to define new resource when changing them (as opposed to e.g. changing LOD range).
